### PR TITLE
Translated PCB to KiCAD

### PR DESCRIPTION
**Pull request by DefProc**
Translated the board into KiCAD 8. 

Open for double checking, but if you'd like to include this that's fine. 

PDFs for review:
[kv4p-ht-1.6-schematic.pdf](https://github.com/user-attachments/files/17401311/kv4p-ht-1.6-schematic.pdf)
[kv4p-ht-1.6-pcb.pdf](https://github.com/user-attachments/files/17401312/kv4p-ht-1.6-pcb.pdf)

### CODE REVIEW

**Comment by kiavash-at-home** [comment]
It seems this is based on version 1.6 which is removed by the latest commit 0db745ceab97506fc33ee2fb4e05a766d37e18f9

**Comment by DefProc** [comment]
Yes, this was translating the 1.6 board. I see from #24 that 1.6 does not have a suitable low-pass filter design. 

I'm updating this to match the 1.7 design, but I think I can see a better RF layout here.

**Comment by VanceVagell** [comment]
Hi Patrick, thanks for working on this. There are now 1 or 2 other
electronics engineers in the #contributors channel on Discord also looking
at PCB updates. You might want to coordinate, or at least consider
different variations you each want to contribute.

**Comment by kiavash-at-home** [comment]
I have looked at the latest KiCAD layout design in [29170bf](https://github.com/VanceVagell/kv4p-ht/pull/26/commits/29170bfd1de29698bacae1e9b3199fc97c5cc267). The filter layout is certainly much more improved than the one posted on EasyEDA. I only have one comment, filters in general are very sensitive to any mutual-coupling between their inductors, I highly recommend to rotate L2 by 90 degrees making it orthogonal to L1 and L3. L1 and L3 seem to be physically far enough that their magnetic field won't couple into each other.

**Comment by VanceVagell** [comment]
It looks like this is still a WIP, please let me know when it's ready for another look (and attach a PDF again, that's helpful). I appreciate your hard work on improving the design and making it available in KiCAD format for people!

**Comment by DefProc** [comment]
> I have looked at the latest KiCAD layout design in [29170bf](https://github.com/VanceVagell/kv4p-ht/pull/26/commits/29170bfd1de29698bacae1e9b3199fc97c5cc267). The filter layout is certainly much more improved than the one posted on EasyEDA. I only have one comment, filters in general are very sensitive to any mutual-coupling between their inductors, I highly recommend to rotate L2 by 90 degrees making it orthogonal to L1 and L3. L1 and L3 seem to be physically far enough that their magnetic field won't couple into each other.

I found a specific reference to this in some testing done [by W0QE](http://w0qe.com/Technical_Topics/coupling_between_coils.html) that seems to suggest the effect is minimal for ferrite cored - presumably because the core is discontinuous between the two inductors - but it's not something I've tested for. 

I agree that filter layout will be important going forwards - hence the current "build and test" cycle of investigation - and guidelines like this are really good for narrowing in on the best compromise of layout and efficiency.

**Pull request closed without merging**
