### PR TITLE
Add GitHub CI Build and SonarCloud Analysis

### PR DESCRIPTION
**Pull request by wsciaroni**
Hey Vance,

I appreciate all the work you've done on this project. I want to help this project succeed by contributing where I can. In this case, I have added a CI pipeline that will ensure builds (and quality) on merge requests to your project (as well as within your project). We can create a SonarCloud project that you can manage. The issues will be "blockers" on new code until you mark them as "Accepted" or whatever you wish. This just lets you be in control of any behavior that makes it in.

Unlike a lot of other static analysis tools that I have used, this one really is minimal overhead and tends to catch some things that would have previously caused substantial issues if released. Feel free to let me know what you think of this.

(GitHub Actions are free on public projects so this is low risk financially).

If you like this, we'll want to do the following:

- [ ] Transfer the SonarCloud project over to your ownership
- [ ] Update the `build.gradle` with the new SonarCloud project key after it is moved.
- [ ] Create the GitHub Secret to hold your `SONAR_TOKEN`

73

## Updates

I have squashed the commits, please update your local branch with the following. Be careful, it includes a force reset...

```bash
git fetch
git checkout main
git reset --hard origin/main
```

### CODE REVIEW

**Comment by wsciaroni** [comment]
These commits need to be squashed before this goes in...

**Comment by VanceVagell** [comment]
Hi Will. I'm not familiar with these services. You mention both CI and static analysis. Will the static analysis happen in Android Studio or in GitHub? And I'm assuming the CI happens after they submit a pull request, and the status is indicated in GitHub? However, I see it's referenced in the build.gradle file in the project, so I'm not sure.

These sound like good improvements, but I want to make sure I understand how this will work before accepting.

**Comment by wsciaroni** [comment]
Hey Vance,

No problem at all! It's great you're keen to understand how this works. Here's a breakdown:

## CI (Continuous Integration)

Think of this as an automated assistant that checks your code every time you make a change. It essentially builds your app and runs tests in a simulated environment (in this case, GitHub Actions) to make sure everything works as expected before it gets merged into the main project. This helps catch errors early on.

The other important thing for software is having a consistent method for creating releases. In the future, I can help you set up GitHub actions to actually release the app (potentially straight to the play store if possible).

## Static Analysis

This is like a spellchecker for your code. It analyzes your code without actually running it, looking for potential issues like bugs, security vulnerabilities, or style inconsistencies. SonarCloud is the tool doing this analysis, and it's really good at catching things that might cause headaches later.

## How It Fits Together

- You make a change to the code and submit a pull request on GitHub.
- GitHub Actions (the CI) kicks in. It automatically builds your app and runs any tests you have set up.
- SonarCloud performs its static analysis. It scans your code for potential problems and reports them back on its platform.
- You see the results of both the build and the analysis on GitHub. If SonarCloud finds any issues, they'll be flagged in the pull request, and you can decide whether to fix them or mark them as "accepted" if they're not a concern.

## The Grade Build

*Disclaimer: This is my first time integrating SonarCloud with gradle, but the following appears to apply from the documentation. The best way to know how it will work is to clone this branch and make sure it doesn't have any unintended consequences.*

You're right to be curious about that!  Adding the SonarQube plugin to your `build.gradle` file does give you the capability to run SonarQube analysis within Android Studio, but it doesn't automatically make it part of the default build.

The plugin provides the tools: That line in your build.gradle essentially equips your project with the necessary tools to communicate with SonarQube. It's like installing a compiler – you have it available, but you need to explicitly tell it to compile your code.

You trigger the analysis: To actually perform the analysis, you need to execute a specific task. This can be done in a few ways:
Command line: You can run the sonarqube task using the command line in your project's directory (e.g., ./gradlew sonarqube).

Android Studio: Android Studio usually provides a way to run Gradle tasks. You can typically find this under the "Gradle" tool window, where you can locate and execute the sonarqube task.

### Why this is helpful:

**Flexibility**: You have control over when the analysis runs. You might not want it to run on every single build, especially for small changes.
**Performance**: Running analysis can take some time. By making it a separate step, you avoid unnecessary overhead during regular development builds.

### SonarLint

Using SonarLint (the SonarQube plugin for Android Studio) is a more efficient way to get continuous feedback. It provides real-time analysis as you code, highlighting potential issues directly in the editor. This helps you catch and fix problems early on, before you even commit your code.

**Comment by VanceVagell** [comment]
Thanks for the explanation. For what it's worth, I'm familiar with CI and static analysis, I meant I'm not familiar with how GitHub integrates with them and what the purpose the Android Studio files is. But you answered that too, I appreciate it!

I'm a little hesitant to accept this because it seems like it could add a significant amount of maintenance overhead for me to make sure this keeps working properly, especially since I have no experience with any of these systems. But some others have asked for something similar, so I will likely revisit this pull request as the project evolves.

**Comment by wsciaroni** [comment]
I will take the maintenance burden if you'd like.


At the moment, this uploads the APK to the GItHub action job. We'll want to move it to the release automatically in the future to make it easier to find.

**Comment by wsciaroni** [comment]
> At the moment, this uploads the APK to the GItHub action job. We'll want to move it to the release automatically in the future to make it easier to find.

Now the apk is getting uploaded when a release is created.

**Comment by VanceVagell** [comment]
Thanks for the work on this. Do I need to configure anything on the GitHub project to make this take effect, or are the configuration files you added enough to do it?

**Comment by VanceVagell** [comment]
I see it has started failing, with this error: 

"Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to".

Based on your pull request description, it sounds like I need to set these in the GitHub project somewhere/somehow. Could you please let me know what's needed so these tools can run properly as actions? Thanks again.

**Comment by VanceVagell** [comment]
I will file this as an issue and assign it to you so we can track follow up work there.

**Comment by VanceVagell** [comment]
It seems I can't assign issues to anyone but myself, so we'll have to figure this out here :) Please let me know what you think. Thanks.

**Pull request merged**
